In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
ruta_csv = '/content/drive/MyDrive/ML/Proyecto_Integrador_Fase_1_ML_SixSeven/features.csv'

df = pd.read_csv(ruta_csv)
print("Dataset cargado correctamente")
print(df.head())

Dataset cargado correctamente
          0         1         2         3         4         5         6  \
0  0.017995  0.383825  0.021868  0.003189  0.000911  0.000228  0.000000   
1  0.001394  0.001394  0.000558  0.001952  0.000558  0.000000  0.000000   
2  0.006127  0.000219  0.000219  0.000875  0.000000  0.000219  0.000438   
3  0.000315  0.000473  0.001103  0.000158  0.000158  0.000788  0.000315   
4  0.001479  0.000296  0.000296  0.000296  0.000000  0.000000  0.000000   

          7         8        9  ...  247  248  249  250  251  252  253  254  \
0  0.000000  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.000000  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.000438  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.000788  0.000788  0.00063  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.000000  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   255               label  
0  0.0  Apple__

In [4]:
df.info

<bound method DataFrame.info of               0         1         2         3         4         5         6  \
0      0.017995  0.383825  0.021868  0.003189  0.000911  0.000228  0.000000   
1      0.001394  0.001394  0.000558  0.001952  0.000558  0.000000  0.000000   
2      0.006127  0.000219  0.000219  0.000875  0.000000  0.000219  0.000438   
3      0.000315  0.000473  0.001103  0.000158  0.000158  0.000788  0.000315   
4      0.001479  0.000296  0.000296  0.000296  0.000000  0.000000  0.000000   
...         ...       ...       ...       ...       ...       ...       ...   
61481  0.043771  0.004987  0.000554  0.000000  0.000000  0.000000  0.000000   
61482  0.028190  0.138468  0.034955  0.000677  0.000000  0.000000  0.000000   
61483  0.158762  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
61484  0.000942  0.005084  0.268328  0.227278  0.015252  0.003389  0.001506   
61485  0.024164  0.036247  0.019771  0.001757  0.000000  0.000220  0.000000   

              7         8        9  ...  247  248  249  250  251  252  253  \
0      0.000000  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1      0.000000  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2      0.000438  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3      0.000788  0.000788  0.00063  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4      0.000000  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...         ...       ...      ...  ...  ...  ...  ...  ...  ...  ...  ...   
61481  0.000000  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
61482  0.000000  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
61483  0.000000  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
61484  0.000377  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
61485  0.000000  0.000000  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       254  255                                   label  
0      0.0  0.0                      Apple___Apple_scab  
1      0.0  0.0                      Apple___Apple_scab  
2      0.0  0.0                      Apple___Apple_scab  
3      0.0  0.0                      Apple___Apple_scab  
4      0.0  0.0                      Apple___Apple_scab  
...    ...  ...                                     ...  
61481  0.0  0.0  Tomato___Tomato_Yellow_Leaf_Curl_Virus  
61482  0.0  0.0  Tomato___Tomato_Yellow_Leaf_Curl_Virus  
61483  0.0  0.0  Tomato___Tomato_Yellow_Leaf_Curl_Virus  
61484  0.0  0.0  Tomato___Tomato_Yellow_Leaf_Curl_Virus  
61485  0.0  0.0  Tomato___Tomato_Yellow_Leaf_Curl_Virus  

[61486 rows x 257 columns]>

In [5]:
X = df.drop('label', axis=1)
y = df['label']

# Partición 80/20 estratificada (mantiene la proporción de las 38 enfermedades)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y  # <--- Esto garantiza representación de las 38 clases
)



In [6]:

model_svc_pca = Pipeline([
    ('scaler', StandardScaler()),

    ('pca', PCA(n_components=0.95)),  # o 138 si quieres fijo

    ('svc', SVC(
        kernel='rbf',
        C=1.0,
        probability=True,
        random_state=42,
        verbose=True
    ))
])

In [7]:
model_svc_pca.fit(X_train, y_train)

[LibSVM]

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=0.95)),
                ('svc', SVC(probability=True, random_state=42, verbose=True))])

In [8]:
y_pred = model_svc_pca.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8748577004390958
                                               precision    recall  f1-score   support

                           Apple___Apple_scab       0.93      0.65      0.76       200
                            Apple___Black_rot       0.81      0.85      0.83       200
                     Apple___Cedar_apple_rust       0.84      0.79      0.81       200
                              Apple___healthy       0.92      0.88      0.90       329
                    Background_without_leaves       0.74      0.94      0.83       229
                          Blueberry___healthy       0.91      0.96      0.94       300
                      Cherry___Powdery_mildew       0.82      0.70      0.75       210
                             Cherry___healthy       0.64      0.80      0.71       200
   Corn___Cercospora_leaf_spot Gray_leaf_spot       0.86      0.81      0.84       200
                           Corn___Common_rust       1.00      0.97      0.99       238
             

In [11]:
import plotly.express as px
import pandas as pd

# Extract the fitted scaler and PCA components from the pipeline
scaler_component = model_svc_pca.named_steps['scaler']
pca_component = model_svc_pca.named_steps['pca']

# Apply the transformations to X_train to get the principal components
X_train_scaled = scaler_component.transform(X_train)
X_train_pca = pca_component.transform(X_train_scaled)

# Creamos un DataFrame temporal para Plotly
df_plot = pd.DataFrame({
    'PC1': X_train_pca[:, 0],
    'PC2': X_train_pca[:, 1],
    'Enfermedad': y_train
})

# Solo graficamos una muestra de 5000 puntos para que no se trabe el navegador
df_sample = df_plot.sample(5000)

fig = px.scatter(
    df_sample, x='PC1', y='PC2',
    color='Enfermedad',
    title="Mapa Interactivo PCA - PlantVillage",
    hover_name='Enfermedad',
    opacity=0.6
)

fig.update_layout(legend_title_text='Patologías')
fig.show()

In [15]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 129    4    0 ...    0    1    0]
 [   0  170    0 ...    0    0    0]
 [   0    0  157 ...    4    0    0]
 ...
 [   0    1    1 ... 1033    0    0]
 [   2    0    0 ...    0  188    0]
 [   0    0    0 ...    0    0  313]]


In [24]:
labels = sorted(set(y_test))

resumen = pd.DataFrame({
    "Clase": labels,
    "Total_real": cm.sum(axis=1),
    "Aciertos": np.diag(cm),
})

resumen["Recall"] = resumen["Aciertos"] / resumen["Total_real"]

resumen.sort_values("Recall", ascending=False)

,Clase,Total_real,Aciertos,Recall
38,Tomato___healthy,318,313,0.984277
9,Corn___Common_rust,238,232,0.974790
36,Tomato___Tomato_Yellow_Leaf_Curl_Virus,1072,1033,0.963619
5,Blueberry___healthy,300,289,0.963333
25,Soybean___healthy,1018,974,0.956778
28,Strawberry___healthy,200,190,0.950000
16,Orange___Haunglongbing_(Citrus_greening),1102,1045,0.948276
37,Tomato___Tomato_mosaic_virus,200,188,0.940000
14,Grape___Leaf_blight_(Isariopsis_Leaf_Spot),215,202,0.939535
4,Background_without_leaves,229,215,0.938865
